// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/dictionary.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class DictionaryRust extends BaseEntrypoint<DictionaryRustApi,
    DictionaryRustApiImpl, DictionaryRustWire> {
  @internal
  static final instance = DictionaryRust._();

  DictionaryRust._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    DictionaryRustApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required DictionaryRustApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<DictionaryRustApiImpl, DictionaryRustWire>
      get apiImplConstructor => DictionaryRustApiImpl.new;

  @override
  WireConstructor<DictionaryRustWire> get wireConstructor =>
      DictionaryRustWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiDictionaryInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 865915332;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'dictionary_bridge',
    ioDirectory: '../crates/dictionary-bridge/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class DictionaryRustApi extends BaseApi {
  Future<void> crateApiDictionaryConfigureIndexCache(
      {required String indexCacheDirectory});

  Future<bool> crateApiDictionaryEnsureMdxIndex({required String mdxPath});

  Future<void> crateApiDictionaryInitApp();

  Future<DictionaryInfo> crateApiDictionaryInspectMdx(
      {required String mdxPath});

  Future<List<DictionaryArticle>> crateApiDictionaryLookupMdx(
      {required String mdxPath, required String query});

  Future<DictionaryResource?> crateApiDictionaryReadMddResource(
      {required String mdxPath,
      required String resourcePath,
      required int maxBytes});

  Future<List<String>> crateApiDictionarySuggestMdx(
      {required String mdxPath, required String prefix, required int limit});
}

class DictionaryRustApiImpl extends DictionaryRustApiImplPlatform
    implements DictionaryRustApi {
  DictionaryRustApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiDictionaryConfigureIndexCache(
      {required String indexCacheDirectory}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(indexCacheDirectory, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDictionaryConfigureIndexCacheConstMeta,
      argValues: [indexCacheDirectory],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionaryConfigureIndexCacheConstMeta =>
      const TaskConstMeta(
        debugName: "configure_index_cache",
        argNames: ["indexCacheDirectory"],
      );

  @override
  Future<bool> crateApiDictionaryEnsureMdxIndex({required String mdxPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(mdxPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDictionaryEnsureMdxIndexConstMeta,
      argValues: [mdxPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionaryEnsureMdxIndexConstMeta =>
      const TaskConstMeta(
        debugName: "ensure_mdx_index",
        argNames: ["mdxPath"],
      );

  @override
  Future<void> crateApiDictionaryInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDictionaryInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionaryInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<DictionaryInfo> crateApiDictionaryInspectMdx(
      {required String mdxPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(mdxPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_dictionary_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDictionaryInspectMdxConstMeta,
      argValues: [mdxPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionaryInspectMdxConstMeta =>
      const TaskConstMeta(
        debugName: "inspect_mdx",
        argNames: ["mdxPath"],
      );

  @override
  Future<List<DictionaryArticle>> crateApiDictionaryLookupMdx(
      {required String mdxPath, required String query}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(mdxPath, serializer);
        sse_encode_String(query, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_dictionary_article,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDictionaryLookupMdxConstMeta,
      argValues: [mdxPath, query],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionaryLookupMdxConstMeta =>
      const TaskConstMeta(
        debugName: "lookup_mdx",
        argNames: ["mdxPath", "query"],
      );

  @override
  Future<DictionaryResource?> crateApiDictionaryReadMddResource(
      {required String mdxPath,
      required String resourcePath,
      required int maxBytes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(mdxPath, serializer);
        sse_encode_String(resourcePath, serializer);
        sse_encode_u_32(maxBytes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_dictionary_resource,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDictionaryReadMddResourceConstMeta,
      argValues: [mdxPath, resourcePath, maxBytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionaryReadMddResourceConstMeta =>
      const TaskConstMeta(
        debugName: "read_mdd_resource",
        argNames: ["mdxPath", "resourcePath", "maxBytes"],
      );

  @override
  Future<List<String>> crateApiDictionarySuggestMdx(
      {required String mdxPath, required String prefix, required int limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(mdxPath, serializer);
        sse_encode_String(prefix, serializer);
        sse_encode_u_32(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDictionarySuggestMdxConstMeta,
      argValues: [mdxPath, prefix, limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionarySuggestMdxConstMeta =>
      const TaskConstMeta(
        debugName: "suggest_mdx",
        argNames: ["mdxPath", "prefix", "limit"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DictionaryResource dco_decode_box_autoadd_dictionary_resource(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_dictionary_resource(raw);
  }

  @protected
  DictionaryArticle dco_decode_dictionary_article(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DictionaryArticle(
      dictionaryName: dco_decode_String(arr[0]),
      headword: dco_decode_String(arr[1]),
      html: dco_decode_String(arr[2]),
    );
  }

  @protected
  DictionaryInfo dco_decode_dictionary_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DictionaryInfo(
      title: dco_decode_String(arr[0]),
      mdxPath: dco_decode_String(arr[1]),
      mddPaths: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  DictionaryResource dco_decode_dictionary_resource(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DictionaryResource(
      resourcePath: dco_decode_String(arr[0]),
      mimeType: dco_decode_String(arr[1]),
      bytes: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<DictionaryArticle> dco_decode_list_dictionary_article(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_dictionary_article).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  DictionaryResource? dco_decode_opt_box_autoadd_dictionary_resource(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_dictionary_resource(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DictionaryResource sse_decode_box_autoadd_dictionary_resource(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_dictionary_resource(deserializer));
  }

  @protected
  DictionaryArticle sse_decode_dictionary_article(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_dictionaryName = sse_decode_String(deserializer);
    var var_headword = sse_decode_String(deserializer);
    var var_html = sse_decode_String(deserializer);
    return DictionaryArticle(
        dictionaryName: var_dictionaryName,
        headword: var_headword,
        html: var_html);
  }

  @protected
  DictionaryInfo sse_decode_dictionary_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_mdxPath = sse_decode_String(deserializer);
    var var_mddPaths = sse_decode_list_String(deserializer);
    return DictionaryInfo(
        title: var_title, mdxPath: var_mdxPath, mddPaths: var_mddPaths);
  }

  @protected
  DictionaryResource sse_decode_dictionary_resource(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_resourcePath = sse_decode_String(deserializer);
    var var_mimeType = sse_decode_String(deserializer);
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    return DictionaryResource(
        resourcePath: var_resourcePath,
        mimeType: var_mimeType,
        bytes: var_bytes);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<DictionaryArticle> sse_decode_list_dictionary_article(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DictionaryArticle>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_dictionary_article(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  DictionaryResource? sse_decode_opt_box_autoadd_dictionary_resource(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_dictionary_resource(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_dictionary_resource(
      DictionaryResource self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dictionary_resource(self, serializer);
  }

  @protected
  void sse_encode_dictionary_article(
      DictionaryArticle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.dictionaryName, serializer);
    sse_encode_String(self.headword, serializer);
    sse_encode_String(self.html, serializer);
  }

  @protected
  void sse_encode_dictionary_info(
      DictionaryInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.mdxPath, serializer);
    sse_encode_list_String(self.mddPaths, serializer);
  }

  @protected
  void sse_encode_dictionary_resource(
      DictionaryResource self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.resourcePath, serializer);
    sse_encode_String(self.mimeType, serializer);
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_dictionary_article(
      List<DictionaryArticle> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_dictionary_article(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_dictionary_resource(
      DictionaryResource? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_dictionary_resource(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
