// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/dictionary.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class DictionaryRustApiImplPlatform
    extends BaseApiImpl<DictionaryRustWire> {
  DictionaryRustApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DictionaryResource dco_decode_box_autoadd_dictionary_resource(dynamic raw);

  @protected
  DictionaryArticle dco_decode_dictionary_article(dynamic raw);

  @protected
  DictionaryInfo dco_decode_dictionary_info(dynamic raw);

  @protected
  DictionaryResource dco_decode_dictionary_resource(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DictionaryArticle> dco_decode_list_dictionary_article(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  DictionaryResource? dco_decode_opt_box_autoadd_dictionary_resource(
      dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DictionaryResource sse_decode_box_autoadd_dictionary_resource(
      SseDeserializer deserializer);

  @protected
  DictionaryArticle sse_decode_dictionary_article(SseDeserializer deserializer);

  @protected
  DictionaryInfo sse_decode_dictionary_info(SseDeserializer deserializer);

  @protected
  DictionaryResource sse_decode_dictionary_resource(
      SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DictionaryArticle> sse_decode_list_dictionary_article(
      SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  DictionaryResource? sse_decode_opt_box_autoadd_dictionary_resource(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dictionary_resource(
      DictionaryResource self, SseSerializer serializer);

  @protected
  void sse_encode_dictionary_article(
      DictionaryArticle self, SseSerializer serializer);

  @protected
  void sse_encode_dictionary_info(
      DictionaryInfo self, SseSerializer serializer);

  @protected
  void sse_encode_dictionary_resource(
      DictionaryResource self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_dictionary_article(
      List<DictionaryArticle> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_dictionary_resource(
      DictionaryResource? self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class DictionaryRustWire implements BaseWire {
  factory DictionaryRustWire.fromExternalLibrary(ExternalLibrary lib) =>
      DictionaryRustWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  DictionaryRustWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
