// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `key_index_path`, `mime_type_for`, `open_dictionary`, `resource_for_bridge`

/// Selects the application-owned directory used for disposable persistent key
/// indexes. This must be called once during startup before dictionaries open.
Future<void> configureIndexCache({required String indexCacheDirectory}) =>
    DictionaryRust.instance.api.crateApiDictionaryConfigureIndexCache(
        indexCacheDirectory: indexCacheDirectory);

/// Opens an MDX file and returns only its display metadata. Content stays in
/// the original location selected by the user.
Future<DictionaryInfo> inspectMdx({required String mdxPath}) =>
    DictionaryRust.instance.api.crateApiDictionaryInspectMdx(mdxPath: mdxPath);

/// Builds and activates a reusable key index for one MDX. The source
/// dictionary remains untouched; only the configured cache directory changes.
Future<bool> ensureMdxIndex({required String mdxPath}) =>
    DictionaryRust.instance.api
        .crateApiDictionaryEnsureMdxIndex(mdxPath: mdxPath);

/// Lazily resolves an image, sound, stylesheet, font, or other attachment
/// from MDD volumes (and approved CSS/font/local-script sidecars) beside an
/// MDX. Dart receives no filesystem handles, only the bounded byte payload
/// needed by its locked-down renderer.
Future<DictionaryResource?> readMddResource(
        {required String mdxPath,
        required String resourcePath,
        required int maxBytes}) =>
    DictionaryRust.instance.api.crateApiDictionaryReadMddResource(
        mdxPath: mdxPath, resourcePath: resourcePath, maxBytes: maxBytes);

/// Returns at most twenty local headword completions without reading article
/// definitions. The cap is enforced again in the core for callers outside the
/// Flutter bridge.
Future<List<String>> suggestMdx(
        {required String mdxPath,
        required String prefix,
        required int limit}) =>
    DictionaryRust.instance.api.crateApiDictionarySuggestMdx(
        mdxPath: mdxPath, prefix: prefix, limit: limit);

/// Looks up a key in one MDX dictionary. The default FRB mode runs this work
/// asynchronously relative to Dart so file parsing cannot block the UI thread.
Future<List<DictionaryArticle>> lookupMdx(
        {required String mdxPath, required String query}) =>
    DictionaryRust.instance.api
        .crateApiDictionaryLookupMdx(mdxPath: mdxPath, query: query);

class DictionaryArticle {
  final String dictionaryName;
  final String headword;
  final String html;

  const DictionaryArticle({
    required this.dictionaryName,
    required this.headword,
    required this.html,
  });

  @override
  int get hashCode =>
      dictionaryName.hashCode ^ headword.hashCode ^ html.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DictionaryArticle &&
          runtimeType == other.runtimeType &&
          dictionaryName == other.dictionaryName &&
          headword == other.headword &&
          html == other.html;
}

class DictionaryInfo {
  final String title;
  final String mdxPath;
  final List<String> mddPaths;

  const DictionaryInfo({
    required this.title,
    required this.mdxPath,
    required this.mddPaths,
  });

  @override
  int get hashCode => title.hashCode ^ mdxPath.hashCode ^ mddPaths.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DictionaryInfo &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          mdxPath == other.mdxPath &&
          mddPaths == other.mddPaths;
}

class DictionaryResource {
  final String resourcePath;
  final String mimeType;
  final Uint8List bytes;

  const DictionaryResource({
    required this.resourcePath,
    required this.mimeType,
    required this.bytes,
  });

  @override
  int get hashCode =>
      resourcePath.hashCode ^ mimeType.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DictionaryResource &&
          runtimeType == other.runtimeType &&
          resourcePath == other.resourcePath &&
          mimeType == other.mimeType &&
          bytes == other.bytes;
}
