use std::fmt;
use std::fs;
use std::path::{Path, PathBuf};

/// A stable identifier generated by the application and stored separately from
/// the source dictionary. It is not derived from a filename because users may
/// rename or move a dictionary after importing it.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct DictionaryId(String);

impl DictionaryId {
    pub fn new(value: impl Into<String>) -> Result<Self, DictionaryError> {
        let value = value.into();
        if value.trim().is_empty() {
            return Err(DictionaryError::InvalidId);
        }
        Ok(Self(value))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// File locations supplied by the platform layer. They may name an original
/// desktop file or an app-private Android performance copy.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DictionarySource {
    pub id: DictionaryId,
    pub mdx_path: PathBuf,
    /// Resource volumes belonging to this MDX. MDict commonly stores these as
    /// `name.mdd`, `name.1.mdd`, `name.2.mdd`, and so on.
    pub mdd_paths: Vec<PathBuf>,
}

impl DictionarySource {
    pub fn new(
        id: DictionaryId,
        mdx_path: impl Into<PathBuf>,
        mdd_path: Option<PathBuf>,
    ) -> Result<Self, DictionaryError> {
        Self::with_mdd_paths(id, mdx_path, mdd_path.into_iter().collect())
    }

    pub fn with_mdd_paths(
        id: DictionaryId,
        mdx_path: impl Into<PathBuf>,
        mdd_paths: Vec<PathBuf>,
    ) -> Result<Self, DictionaryError> {
        let source = Self {
            id,
            mdx_path: mdx_path.into(),
            mdd_paths,
        };
        source.validate_extensions()?;
        Ok(source)
    }

    /// Creates a source and discovers conventional MDD sidecars next to the
    /// selected MDX. Only the same base name and numbered continuations are
    /// accepted, so unrelated dictionaries in the same folder stay separate.
    pub fn discover(
        id: DictionaryId,
        mdx_path: impl Into<PathBuf>,
    ) -> Result<Self, DictionaryError> {
        let mdx_path = mdx_path.into();
        let mdd_paths = Self::discover_mdd_paths(&mdx_path)?;
        Self::with_mdd_paths(id, mdx_path, mdd_paths)
    }

    pub fn discover_mdd_paths(mdx_path: &Path) -> Result<Vec<PathBuf>, DictionaryError> {
        validate_extension(mdx_path, "mdx")?;

        let parent = mdx_path
            .parent()
            .ok_or_else(|| DictionaryError::ResourceDiscovery {
                path: mdx_path.to_path_buf(),
                message: "the MDX file has no parent folder".to_owned(),
            })?;
        let base_name = mdx_path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .ok_or_else(|| DictionaryError::ResourceDiscovery {
                path: mdx_path.to_path_buf(),
                message: "the MDX filename is not valid UTF-8".to_owned(),
            })?
            .to_ascii_lowercase();

        let entries = fs::read_dir(parent).map_err(|error| DictionaryError::ResourceDiscovery {
            path: parent.to_path_buf(),
            message: error.to_string(),
        })?;

        let mut matches = Vec::new();
        for entry in entries {
            let entry = entry.map_err(|error| DictionaryError::ResourceDiscovery {
                path: parent.to_path_buf(),
                message: error.to_string(),
            })?;
            // Android SAF documents are exposed to Rust through private
            // symlinks to read-only file descriptors. `file_type` describes
            // the link itself, while metadata follows it and correctly
            // identifies the original MDD as a regular file.
            if !fs::metadata(entry.path())
                .map_err(|error| DictionaryError::ResourceDiscovery {
                    path: parent.to_path_buf(),
                    message: error.to_string(),
                })?
                .is_file()
            {
                continue;
            }
            let path = entry.path();
            let Some(order) = mdd_volume_order(&path, &base_name) else {
                continue;
            };
            matches.push((order, path));
        }

        matches.sort_unstable_by(|(left_order, left_path), (right_order, right_path)| {
            left_order
                .cmp(right_order)
                .then_with(|| left_path.cmp(right_path))
        });
        Ok(matches.into_iter().map(|(_, path)| path).collect())
    }

    /// Proposes the conventional sidecar file, without checking the file
    /// system. The importer decides whether it exists and is readable.
    pub fn adjacent_mdd_path(&self) -> PathBuf {
        self.mdx_path.with_extension("mdd")
    }

    fn validate_extensions(&self) -> Result<(), DictionaryError> {
        validate_extension(&self.mdx_path, "mdx")?;
        for path in &self.mdd_paths {
            validate_extension(path, "mdd")?;
        }
        Ok(())
    }
}

fn mdd_volume_order(path: &Path, base_name: &str) -> Option<u32> {
    if !path.extension()?.to_str()?.eq_ignore_ascii_case("mdd") {
        return None;
    }

    let stem = path.file_stem()?.to_str()?.to_ascii_lowercase();
    if stem == base_name {
        return Some(0);
    }

    let suffix = stem.strip_prefix(base_name)?.strip_prefix('.')?;
    suffix.parse::<u32>().ok()?.checked_add(1)
}

fn validate_extension(path: &Path, expected: &'static str) -> Result<(), DictionaryError> {
    let actual = path
        .extension()
        .and_then(|extension| extension.to_str())
        .map(|extension| extension.to_ascii_lowercase());

    if actual.as_deref() == Some(expected) {
        Ok(())
    } else {
        Err(DictionaryError::UnexpectedExtension {
            path: path.to_path_buf(),
            expected,
        })
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DictionaryMetadata {
    pub id: DictionaryId,
    pub title: String,
    pub description: Option<String>,
}

/// An individual record. `html` has not been rendered or trusted; callers must
/// display it in a locked-down renderer that disables network and JavaScript.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Article {
    pub dictionary_id: DictionaryId,
    pub headword: String,
    pub html: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct LookupResult {
    pub query: String,
    pub articles: Vec<Article>,
}

/// A resource resolved from an MDD sidecar. The path is the physical MDD key,
/// not a filesystem path, and `bytes` is bounded by the caller's limit.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DictionaryResource {
    pub path: String,
    pub bytes: Vec<u8>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum DictionaryError {
    InvalidId,
    UnexpectedExtension {
        path: PathBuf,
        expected: &'static str,
    },
    Open {
        path: PathBuf,
        message: String,
    },
    Lookup {
        query: String,
        message: String,
    },
    Suggestion {
        prefix: String,
        message: String,
    },
    Index {
        path: PathBuf,
        message: String,
    },
    ResourceDiscovery {
        path: PathBuf,
        message: String,
    },
    Resource {
        path: String,
        message: String,
    },
    ResourceTooLarge {
        path: String,
        size: u64,
        max_size: usize,
    },
}

impl fmt::Display for DictionaryError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidId => write!(formatter, "dictionary identifier cannot be empty"),
            Self::UnexpectedExtension { path, expected } => {
                write!(formatter, "expected a .{expected} file: {}", path.display())
            }
            Self::Open { path, message } => {
                write!(formatter, "could not open {}: {message}", path.display())
            }
            Self::Lookup { query, message } => {
                write!(formatter, "could not look up {query:?}: {message}")
            }
            Self::Suggestion { prefix, message } => {
                write!(
                    formatter,
                    "could not suggest entries for {prefix:?}: {message}"
                )
            }
            Self::Index { path, message } => {
                write!(
                    formatter,
                    "could not use key index {}: {message}",
                    path.display()
                )
            }
            Self::ResourceDiscovery { path, message } => {
                write!(
                    formatter,
                    "could not discover resources near {}: {message}",
                    path.display()
                )
            }
            Self::Resource { path, message } => {
                write!(formatter, "could not read resource {path:?}: {message}")
            }
            Self::ResourceTooLarge {
                path,
                size,
                max_size,
            } => write!(
                formatter,
                "resource {path:?} is {size} bytes, above the {max_size}-byte limit"
            ),
        }
    }
}

impl std::error::Error for DictionaryError {}

#[cfg(test)]
mod tests {
    use super::mdd_volume_order;
    use std::path::Path;

    #[test]
    fn detects_a_base_mdd_and_numbered_volumes() {
        assert_eq!(mdd_volume_order(Path::new("oaldpe.mdd"), "oaldpe"), Some(0));
        assert_eq!(
            mdd_volume_order(Path::new("OALDPE.2.MDD"), "oaldpe"),
            Some(3)
        );
        assert_eq!(mdd_volume_order(Path::new("other.1.mdd"), "oaldpe"), None);
        assert_eq!(mdd_volume_order(Path::new("oaldpe.mdx"), "oaldpe"), None);
    }
}
